### ISSUE TITLE
python2.7+ubuntu

### ISSUE THREAD

**Issue by huiminyan2017** [bonfy/leetcode#14]
折腾了半天，终于跑通了，
环境：python2.7，ubuntu
中间出现了几个问题，记得的如下：
pip install futures；(python2.7)
在github上创建好repository,需要在linux下leetcode_generate.py代码目录先执行下git init 
339行改成question  = HTMLParser.HTMLParser().unescape(question) (python2.7, 需要先import HTMLParser)

**Comment by bonfy** [comment]
works in python3， python 2.7 maybe
