### ISSUE TITLE
Windows 环境报错

### ISSUE THREAD

**Issue by RazorBach** [bonfy/leetcode#17]
首先是[这个issue](https://github.com/bonfy/leetcode/issues/15)
改了以后cookies.json生成了，但是碰到下面问题：
> Traceback (most recent call last):
  File "leetcode_generate.py", line 513, in <module>
    do_job(leetcode)
  File "leetcode_generate.py", line 489, in do_job
    leetcode.load()
  File "leetcode_generate.py", line 235, in load
    self.load_items_from_api()
  File "leetcode_generate.py", line 220, in load_items_from_api
    self.items = list(self._generate_items_from_api(rst))
  File "leetcode_generate.py", line 248, in _generate_items_from_api
    data['is_paid'] = json_data['is_paid']
KeyError: 'is_paid'
把is_paid注释掉，然后Line 143 改成
```
@property
    def is_lock(self):
        # return not self.is_paid and self.paid_only
        return self.paid_only
```
再跑就卡住不动了··好像是request连接超时··求解决下

**Comment by Kiwitwitter** [comment]
I have the same problem on Mac after fixing [this issue](https://github.com/bonfy/leetcode/issues/15) by instructed.

**Comment by bonfy** [comment]
leetcode 又改版了，初步看了下， 去掉了 登陆界面的 id_remember, API 里面去掉了 is_paid 这个字段

由于 phantomjs 这个项目也不维护了，近期可能对代码做一次大的优化，具体时间不能保证，只能说尽快。

感谢各位支持和关注。

**Comment by bonfy** [comment]
@ftdejo @Kiwitwitter  It can work in CentOS and MacOS now. Use chromedriver replace phantomjs now. Windows I think can work as well.

**Comment by Kiwitwitter** [comment]
@bonfy Thank you, it worked well!
