### ISSUE TITLE
python脚本优化建议

### ISSUE THREAD

**Issue by fancymax** [bonfy/leetcode#2]
- [x] 增加所有leetcode支持的语言。

- [x] Readme优化，目前只要是解决过的问题都会生成一个链接。
应该限制为：解决过的问题并且是config设置的语言才生成链接。

**Comment by bonfy** [comment]
谢谢宝贵建议

第一个已经增加

第二个优化 由于 [https://leetcode.com/api/problems/algorithms/](https://leetcode.com/api/problems/algorithms/) 没有涉及到具体pass的语言， 目前考虑先从submissions加载一遍所有设置语言的solutions，然后生成readme

**Comment by bonfy** [comment]
增加了对 Readme的优化，config设置的语言才会生成链接
