### ISSUE TITLE
i think leetcode changes his website again

### ISSUE THREAD

**Issue by mengban** [bonfy/leetcode#25]
emmmmm....
the log as follows:
`
  File ".\leetcode_generate.py", line 611, in <module>
    do_job(leetcode)
  File ".\leetcode_generate.py", line 588, in do_job
    leetcode.load()
  File ".\leetcode_generate.py", line 263, in load
    self.load_submissions()
  File ".\leetcode_generate.py", line 320, in load_submissions
    assert resp.status_code == 200
AssertionError
`
ORZ

**Comment by mengban** [comment]
And another question is that after running the script , my account in browser was loged out.

**Comment by johnnysuns** [comment]
@mengban In` load_submissions()`, `Session.get()`, line 319, could failed. So I simply add a retry mechanism when resp.status_code != 200 and it works. see my version [leetcode_generate.py](https://github.com/johnnysuns/leetcode_relax/blob/master/leetcode_generate.py) in line 324

**Comment by mengban** [comment]
It works. @johnnysuns The beauty of brute force!!!

**Comment by bonfy** [comment]
@mengban @johnnysuns 

I add time.sleep(2.5) when load submissions .And it works now.

Leetcode change its website policy and will return 403 if you load submissions too frequent.

**Comment by mengban** [comment]
@bonfy niubility bro.
