### ISSUE TITLE
Only downloaded 6 problems for me

### ISSUE THREAD

**Issue by Mountainheld** [bonfy/leetcode#32]
Hi, thanks for the generator!! It is really awesome!! However I came across the issue that I have 13 problems marked as solved on my Leetcode account. But the generator only downloaded 6 of them. Is there any specific parameter I need to adjust?

**Comment by bonfy** [comment]
@Mountainheld 

Maybe you use different languages to solve the 13 problems. Please set the language in the config file.
* Follow https://github.com/bonfy/leetcode/blob/master/README_leetcode_generate.md
* Set the config language 
* Notice that python3 and python is two different language

May this can help you.
