### ISSUE TITLE
In my local machine,exception always raise, but actually it has got the cookie. Don't know why it can't get PHPSESSID key value.

### ISSUE THREAD

**Issue by songkaiape** [bonfy/leetcode#7]
if not self.session.cookies.get('PHPSESSID'):
      raise Exception('Login Error')

I use status_code to determine if login is OK and it can work normally.

**Comment by bonfy** [comment]
Thank you for your question.

status_code: 200 means you can connect to the leetcode website ,but it can't determine if the login is OK.

If you can't get the PHPSESSID, then you login failed.

you can set the username and password in the config.cfg first. And you can also login with the set username and password in the browser to see if your username and password is correct.

```
[leetcode]

username = username
password = password
language = python
repo = https://github.com/bonfy/leetcode
```

**Comment by bonfy** [comment]
the leetcode website changes the name "PHPSESSID" to "LEETCODE_SESSION" to store its session id.

I have fixed it now.

Thank you for your problem.

I think you should use the session to determine if you have logged in. status_code:200 can only determine whether you can connect to leetcode website. For example , if you use a wrong username and password, status_code is also 200, but you not login, and the code can't work.

**Comment by songkaiape** [comment]
Thx for explanation
