### ISSUE TITLE
self._load_solution_language() error

### ISSUE THREAD

**Issue by fancymax** [bonfy/leetcode#8]
Leetcode login
Traceback (most recent call last):
 line 461, in <module>
    main()
 line 441, in main
    leetcode.load()
line 247, in load
    self._load_solution_language()
 line 200, in _load_solution_language
    assert r.status_code == 200
AssertionError

the py script is not work?

**Comment by bonfy** [comment]
@fancymax I'm fixing it now.Almost done, maybe this weekend can release the new version(can't promise).
 
the reason was leetcode change his website:

1. the way to login. the csrftoken encrypt
2. submissions change from HTML to JSON

**Comment by fancymax** [comment]
@bonfy thank you very much,👍

**Comment by bonfy** [comment]
@fancymax 

It can work now.But should install two more things

`PhantomJS` and `selenium`

Mac can Install `PhantomJS` by Homebrew, `selenium` can pip install

I use `selenium` and `PhantomJS` to login first and save the cookies to a local file. Then pass the cookies to requests.

It's not the best way I think, but I can't find the algorithm Leetcode encrypt the csrftoken...

**Comment by fancymax** [comment]
@bonfy thanks very much,it works right.
